### ISSUE TITLE
The tester stuck in Parsing hell

### ISSUE THREAD

**Issue by yamennaani** [zstenger93/42_minishell_tester#18]
the tester takes a long time in the Parsing Hell, sometimes it just freeze , and the terminal doesn't response.
Even so i test the cases manually and everything was ok

**Comment by zstenger93** [comment]
Well, we never experienced that nor heard it from anyone though most people are using it on our campus as well so with this amount of information I can't do much about it.

1. Are you sure you have tried the tests the same way as the tester does?
2. Did you try to find which test/s causing it in the tester by commenting them out and going through them individually to see what's happening?
3. Is it only the parsing hell?

Honestly, I can't do much without specific information, even then not sure what to do with it cause it sounds weird that only this part breaks somehow, but if you try them separately it goes just fine.
Sounds more like there is a small problem which won't be much separately but multiple times it's crashing

**Comment by yamennaani** [comment]
hi so thank u for responding.
so as u said it was a small problem which cause a big problems later

**Comment by zstenger93** [comment]
Nice, glad you have found it!
